name = "Vinoxio"
author = "vixeliz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f6298b548646b4e3b44833443b3e3ae3f5d837855b860e4a565dc09df808059"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
datapack-folder = "paxi/datapacks"
