name = "Vinox"
author = "Vixeliz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ccbde4038200fc2937538f84674bc32baea0889e45b8ea00f22cab663a9add7"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
