name = "Vinox"
author = "Vixeliz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60781907f156d79a0ecf169043b582fa48b4cc4f718b7d7d32b014fdf1994a3f"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
