#One source mana(Ars) to X Mana(Bot)
mana_convert = 30.0
#Max rate of mana transfer
max_rate = 2000

[player_mana_convert]
	#Enable player mana convert
	enable = true
	#Allow charging items using player's mana recovery
	charge = true
	#One player mana(Ars) to X Mana(Bot) [Referred when receiving/extracting ars-nouveau mana]
	a2b = 8.0
	#One Mana(Bot) to X player mana(Ars) [Referred when receiving/extracting botania mana]
	b2a = 0.012

